/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetointegrador;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author allan
 */
public class ConsultarPerguntasTela extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarPerguntasTela
     */
    public ConsultarPerguntasTela() {
        super("Consultar Perguntas");
        initComponents();
        setLocationRelativeTo(null);
        try {
            obterPerguntas();
        } catch (Exception ex) {
            Logger.getLogger(ConsultarPerguntasTela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void obterPerguntas() throws Exception{
        try {
            var dao = new QuestaoDAO();
            var rs = dao.obterPerguntas();
            var rsmd = rs.getMetaData();
            int cols = rsmd.getColumnCount();
            DefaultTableModel model = (DefaultTableModel) perguntasTable.getModel();
            String[] colName = new String[cols];
            for(int i=0; i < cols; i++)
                colName[i]=rsmd.getColumnName(i+1);
            model.setColumnIdentifiers(colName);
            String id, alternativa1, alternativa2, alternativa3, alternativa4, Pergunta, Resposta, Pontos;
            while(rs.next()){
                id = rs.getString(1);
                alternativa1 = rs.getString(2);
                alternativa2 = rs.getString(3);
                alternativa3 = rs.getString(4);
                alternativa4 = rs.getString(5);
                Pergunta = rs.getString(6);
                Resposta = rs.getString(7);
                Pontos = rs.getString(8);
                String[]row = {id, alternativa1, alternativa2, alternativa3, alternativa4, Pergunta, Resposta, Pontos};
                model.addRow(row);
            }
            rs.close();
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        perguntasTable = new javax.swing.JTable();
        voltarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(69, 134, 198));

        jPanel1.setBackground(new java.awt.Color(69, 134, 198));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consulte o ID das perguntas aqui");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 229, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        perguntasTable.setBackground(new java.awt.Color(55, 108, 160));
        perguntasTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        perguntasTable.setForeground(new java.awt.Color(255, 255, 255));
        perguntasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        perguntasTable.setToolTipText("");
        perguntasTable.setGridColor(new java.awt.Color(55, 108, 160));
        perguntasTable.setSelectionBackground(new java.awt.Color(77, 154, 229));
        perguntasTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                perguntasTableComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(perguntasTable);
        perguntasTable.setFillsViewportHeight( true );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 828;
        gridBagConstraints.ipady = 330;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(voltarButton, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void perguntasTableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_perguntasTableComponentShown

    }//GEN-LAST:event_perguntasTableComponentShown

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        var mq = new ManterQuestao();
        mq.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarPerguntasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarPerguntasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarPerguntasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarPerguntasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarPerguntasTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable perguntasTable;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
